import { ChartView, colorFor, formatNumber, displayValue } from './renderer.js';
import { defaultWorkbook, genericWorkbook, newSheet, sourceFromDescription, fieldInfo, measurePill, chartQuery, chartModel, WorkbookHistory, validateWorkbook, uid } from './model.js';
import { toCSV } from './core.js';
import { expressionFunctions } from './expression.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={
 database:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0"/>',
 search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',
 undo:'<path d="m8 5-5 5 5 5M3 10h10a6 6 0 0 1 0 12"/>',redo:'<path d="m16 5 5 5-5 5m5-5H11a6 6 0 0 0 0 12"/>',
 save:'<path d="M4 3h13l4 4v14H3V3zM7 3v6h9V3M7 21v-7h10v7"/>',
 sheet:'<path d="M5 3h11l4 4v14H5zM16 3v5h4M8 16v-4m4 4v-6m4 6v-3"/>',
 duplicate:'<path d="M9 8h12v13H9zM4 16H2V2h13v3M12 17v-4m3 4v-6m3 6v-3"/>',
 clear:'<path d="m4 15 9-11 7 6-9 11H8zM10 9l7 6M13 21h8"/>',
 swap:'<path d="M4 7h15m-4-4 4 4-4 4M20 17H5m4-4-4 4 4 4"/>',
 'sort-asc':'<path d="M6 20V4m-3 3 3-3 3 3M12 6h3m-3 6h6m-6 6h9"/>',
 'sort-desc':'<path d="M6 4v16m-3-3 3 3 3-3M12 6h9m-9 6h6m-6 6h3"/>',
 group:'<path d="M3 3h7v7H3zm11 0h7v7h-7zM3 14h7v7H3zm11 0h7v7h-7z"/><path d="M12 4v16M4 12h16" stroke-dasharray="1 2"/>',
 join:'<circle cx="8" cy="12" r="6"/><circle cx="16" cy="12" r="6"/>',
 export:'<path d="M4 14v7h16v-7M12 17V3m-5 5 5-5 5 5"/>',
 grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
 dashboard:'<rect x="3" y="3" width="18" height="18" rx="1"/><path d="M3 10h18M12 10v11"/>',
 bar:'<path d="M3 3v18h18M7 17v-6h3v6zm6 0V6h3v11zm6 0v-9h3v9z"/>',
 line:'<path d="M3 3v18h18M5 16l5-7 5 3 6-8"/><path d="m5 12 5 3 5-7 6 5" opacity=".3"/>',
 scatter:'<path d="M3 3v18h18"/><circle cx="8" cy="14" r="1.4"/><circle cx="11" cy="9" r="1.3"/><circle cx="15" cy="12" r="1.5"/><circle cx="19" cy="6" r="1.4"/><circle cx="17" cy="17" r="1"/><circle cx="8" cy="6" r="1"/>',
 heatmap:'<path d="M3 3h5v5H3zm8 0h5v5h-5zm8 0h5v5h-5zM3 11h5v5H3zm8 0h5v5h-5zm8 0h5v5h-5zM3 19h5v5H3zm8 0h5v5h-5zm8 0h5v5h-5z"/>',
 table:'<rect x="3" y="4" width="18" height="16" rx="1"/><path d="M3 9h18M3 14h18M9 4v16m6-16v16"/>',
 columns:'<rect x="3" y="4" width="18" height="16" rx="1"/><path d="M9 4v16m6-16v16"/>',
 rows:'<rect x="3" y="4" width="18" height="16" rx="1"/><path d="M3 9h18M3 14h18"/>',
 filter:'<path d="M3 4h18l-7 8v8l-4-2v-6z"/>',
 color:'<circle cx="8" cy="9" r="5"/><circle cx="16" cy="9" r="5"/><circle cx="12" cy="16" r="5"/>',
 size:'<circle cx="7" cy="15" r="3"/><circle cx="17" cy="8" r="5"/>',
 label:'<path d="M4 5h16M12 5v15M8 20h8"/>',
 detail:'<path d="M4 5h2m4 0h10M4 12h2m4 0h10M4 19h2m4 0h10"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18m-14 4h2m4 0h2m-8 4h2"/>',
 edit:'<path d="m4 16 12-12 4 4L8 20l-5 1zM13 7l4 4"/>',
 sparkle:'<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3zM21 2v4m-2-2h4"/>',
 link:'<path d="m9 15 6-6M8 16l-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m5 1 2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0" transform="translate(0 0) scale(.9)"/>',
 info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',
 arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
 refresh:'<path d="M20 11a8 8 0 0 0-14-5L3 9m0-6v6h6M4 13a8 8 0 0 0 14 5l3-3m0 6v-6h-6"/>'
};
const icon=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true">${icons[name]??icons.sheet}</svg>`;
const typeName={bar:'Bars',line:'Lines',scatter:'Scatter',heatmap:'Heatmap',table:'Text table'};
const count=n=>new Intl.NumberFormat('en-US').format(n);

class WorkerClient {
  constructor(){this.pending=new Map();this.nextId=0;const embedded=globalThis.__LATTICE_WORKER_SOURCE__;this.url=embedded?URL.createObjectURL(new Blob([embedded],{type:'text/javascript'})):new URL('./worker.js',import.meta.url);this.worker=new Worker(this.url,{type:embedded?'classic':'module',name:'lattice-query-engine'});this.worker.onmessage=({data})=>{const p=this.pending.get(data.id);if(!p)return;clearTimeout(p.timer);this.pending.delete(data.id);if(data.error)p.reject(new Error(data.error.message));else p.resolve(data.value);};this.worker.onerror=e=>{for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(new Error(e.message||'The analytics worker stopped.'));}this.pending.clear();};}
  call(method,args={}){return new Promise((resolve,reject)=>{const id=++this.nextId;const timer=setTimeout(()=>{this.pending.delete(id);reject(new Error(`${method} exceeded the 120-second worker deadline.`));},120000);this.pending.set(id,{resolve,reject,timer});this.worker.postMessage({id,method,args});});}
  dispose(){this.worker.terminate();for(const p of this.pending.values())clearTimeout(p.timer);if(typeof this.url==='string')URL.revokeObjectURL(this.url);}
}
class LocalStore {
  async open(){try{this.db=await new Promise((resolve,reject)=>{const req=indexedDB.open('lattice-analytics-v1',1);req.onupgradeneeded=()=>{req.result.createObjectStore('metadata');req.result.createObjectStore('sources',{keyPath:'id'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});return true;}catch{this.db=null;return false;}}
  async read(store,key){if(!this.db)return null;return new Promise((resolve,reject)=>{const tx=this.db.transaction(store),r=tx.objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
  async save(workbook,sources){if(!this.db)throw new Error('Browser storage is unavailable. Export a workbook file to save your work.');return new Promise((resolve,reject)=>{const tx=this.db.transaction(sources?['metadata','sources']:['metadata'],'readwrite');tx.objectStore('metadata').put(structuredClone(workbook),'current');if(sources)for(const source of sources)tx.objectStore('sources').put(source);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error??new Error('Storage transaction aborted.'));});}
}
const rpc=new WorkerClient(),store=new LocalStore(),history=new WorkbookHistory();
let workbook=null,selection=null,views=new Map(),results=new Map(),renderEpoch=0,queryEpoch=0,saveTimer=null,dataDirty=false,saveInFlight=null,saveVersion=0;
let dashboardEditing=false,focusedSheetId=null,analyticsTab=false,fieldSearch='',currentMode='Canvas2D';
const activeSource=()=>workbook?.sources.find(s=>s.id===workbook.activeSource)??workbook?.sources[0];
const sourceFor=s=>workbook.sources.find(d=>d.id===s.source);
const activeDashboard=()=>workbook?.active.kind==='dashboard'?workbook.dashboards.find(d=>d.id===workbook.active.id):null;
const activeSheet=()=>workbook?.active.kind==='sheet'?workbook.sheets.find(s=>s.id===workbook.active.id):workbook?.sheets.find(s=>s.id===focusedSheetId)??workbook?.sheets.find(s=>s.id===activeDashboard()?.tiles[0]?.sheetId)??workbook?.sheets[0];
const sheetById=id=>workbook.sheets.find(s=>s.id===id);
function toast(message,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('#toast-stack').append(el);setTimeout(()=>el.remove(),type==='error'?9000:4600);}
function fail(error){console.error(error);toast(error.message??String(error),'error');}
function updateDescription(d){const at=workbook.sources.findIndex(s=>s.id===d.id);if(at>=0)workbook.sources[at]={...workbook.sources[at],...d};return workbook.sources[at];}
function markChanged(needsData=false){saveVersion++;dataDirty||=needsData;$('#saved-indicator').textContent='Unsaved changes';clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveLocal(false).catch(fail),550);}
async function saveLocal(notify=true){
  if(!store.db){$('#saved-indicator').textContent='File export available';if(notify)toast('Browser storage is unavailable here. Download a .lattice workbook to save your work.');return;}
  if(saveInFlight){await saveInFlight;if(dataDirty)return saveLocal(notify);return;}
  const version=saveVersion;saveInFlight=(async()=>{const sources=dataDirty?await rpc.call('snapshot'):null;await store.save(workbook,sources);if(version===saveVersion){dataDirty=false;$('#saved-indicator').textContent='Saved locally';}if(notify)toast('Workbook saved in this browser.','success');})();
  try{await saveInFlight;}finally{saveInFlight=null;}
}
function mutate(label,fn,{data=false,render=true}={}){const redo=history.redoStack;history.push(workbook,label);try{fn();}catch(error){workbook=history.undoStack.pop().state;history.redoStack=redo;renderAll();throw error;}markChanged(data);if(render)renderAll();else updateHistoryButtons();}
function updateHistoryButtons(){$('#undo-button').disabled=!history.undoStack.length;$('#redo-button').disabled=!history.redoStack.length;$('#undo-button').title=history.undoStack.length?`Undo ${history.undoStack.at(-1).label} (Ctrl/⌘ Z)`:'Undo';}
async function syncDefinitions(){for(const source of workbook.sources){const d=await rpc.call('definitions',{tableId:source.id,definitions:source.definitions??[]});updateDescription(d);}}
async function historyStep(direction){
  const stack=direction==='undo'?history.undoStack:history.redoStack;if(!stack.length)return;
  const entry=stack.at(-1),currentData=entry.data?await rpc.call('snapshot'):null;
  const previous=history[direction](workbook);if(!previous)return;
  const inverse=direction==='undo'?history.redoStack.at(-1):history.undoStack.at(-1);if(currentData)inverse.data=currentData;
  workbook=previous.state;selection=null;
  if(previous.data)await rpc.call('restore',{sources:previous.data});await syncDefinitions();markChanged(!!previous.data);renderAll();toast(`${direction==='undo'?'Undid':'Redid'} ${previous.label}.`);
}
function setActive(kind,id){workbook.active={kind,id};selection=null;if(kind==='sheet'){const s=sheetById(id);workbook.activeSource=s.source;focusedSheetId=id;}if(kind==='dashboard'){const d=activeDashboard();workbook.activeSource=d.source??workbook.activeSource;focusedSheetId=d.tiles[0]?.sheetId??null;}dashboardEditing=false;markChanged();renderAll();}
function renderAll(){if(!workbook)return;renderEpoch++;queryEpoch++;disposeViews();$('#workbook-name').textContent=workbook.name;document.title=`Lattice Analytics — ${workbook.name}`;renderFields();renderTabs();renderRightPane();updateHistoryButtons();const active=workbook.active.kind;if(active==='dashboard')renderDashboard();else if(active==='sheet')renderWorksheet();else renderDataSource();refreshQueries().catch(fail);}
function disposeViews(){for(const view of views.values())view.chart.dispose();views.clear();}
function fieldGlyph(f){return f.calculated?'ƒx':f.type==='number'?'#':f.type==='date'?'▦':f.type==='boolean'?'◐':'Abc';}
function renderFields(){const source=activeSource();if(!source)return;$('#source-select').innerHTML=workbook.sources.map(s=>`<option value="${esc(s.id)}" ${s.id===source.id?'selected':''}>${esc(s.name)}</option>`).join('');$('#source-row-count').textContent=`${count(source.rows)} rows`;$('#source-caption').textContent=source.name;$('#storage-info').textContent=`${formatNumber(source.bytes/1048576)} MB · Columnar extract`;
  $$('.pane-tabs>button').slice(0,2).forEach((el,i)=>el.classList.toggle('active',i===(analyticsTab?1:0)));
  if(analyticsTab){$('#field-list').innerHTML=`<div class="analytics-card"><h4>Query inspector</h4>Explore the relational plan, scanned rows, and incremental cache for the active visualization.<button data-action="analysis">Inspect execution ${icon('arrow')}</button></div><div class="analytics-card"><h4>Calculated fields</h4>Type-checked expressions with numeric, string, conditional, and date functions.<button data-action="calculation">Create a calculation ${icon('arrow')}</button></div><div class="analytics-card"><h4>Live append</h4>Cached aggregates scan only newly appended rows. Previous aggregates are reused.<button data-action="append">Append CSV / JSON ${icon('arrow')}</button></div><div class="analytics-card"><h4>Join data</h4>Inner, left, and full joins. Composite keys and many-to-many matches are supported.<button data-action="join">Open join editor ${icon('arrow')}</button></div>`;return;}
  const fields=source.schema.map(f=>fieldInfo(source,{field:f.name})).filter(f=>f.name.toLowerCase().includes(fieldSearch.toLowerCase()));
  const section=(role,title)=>{const list=fields.filter(f=>f.role===role);return `<div class="field-heading">${title}<span class="field-count">${list.length}</span></div>${list.map(f=>`<div class="field-item ${role} ${f.calculated?'calculated':''}" draggable="true" data-field="${esc(f.name)}" data-source="${esc(source.id)}" tabindex="0" role="button" title="${esc(f.name)} · ${f.type} · ${role}. Drag to a shelf, or double-click."><span class="field-type">${fieldGlyph(f)}</span><span class="field-name">${esc(f.name)}</span><button class="field-options" aria-label="Options for ${esc(f.name)}">⌄</button></div>`).join('')}`;};
  $('#field-list').innerHTML=section('dimension','Dimensions')+'<div class="field-divider"></div>'+section('measure','Measures')+`<div class="field-hint">Drag a field to a shelf to explore.<br>Double-click to add it automatically.</div>`;
}
function renderTabs(){$('#sheet-tabs').innerHTML=[...workbook.sheets.map(s=>`<button class="sheet-tab ${workbook.active.kind==='sheet'&&workbook.active.id===s.id?'active':''}" data-open-sheet="${esc(s.id)}" title="${esc(s.name)} · Right-click for options">${icon(s.type)}${esc(s.name)}${workbook.active.id===s.id?'<i class="tab-dot"></i>':''}</button>`),...workbook.dashboards.map(d=>`<button class="sheet-tab ${workbook.active.kind==='dashboard'&&workbook.active.id===d.id?'active':''}" data-open-dashboard="${esc(d.id)}">${icon('dashboard')}${esc(d.name)}${workbook.active.id===d.id?'<i class="tab-dot"></i>':''}</button>`)].join('');$('.data-source-tab').classList.toggle('active',workbook.active.kind==='data');}
function renderRightPane(){const sheet=activeSheet(),dashboard=activeDashboard();const source=sheet?sourceFor(sheet):activeSource();const bound=sheet?.marks.color,legendField=bound&&fieldInfo(source,bound)?.role==='dimension'?bound.field:null;
  $('#right-pane').innerHTML=`<div class="right-heading">Show Me<button data-action="toggle-show-me" title="Hide visualization pane">×</button></div><div class="right-section"><h4>Visualization</h4><div class="chart-types">${['bar','line','scatter','heatmap','table'].map(type=>`<button class="chart-type ${sheet?.type===type?'active':''}" data-chart-type="${type}" title="Use ${typeName[type]} for ${esc(sheet?.name??'new worksheet')}">${icon(type)}<span>${typeName[type]}</span></button>`).join('')}<button class="chart-type" data-action="new-dashboard" title="Create a dashboard">${icon('dashboard')}<span>Dashboard</span></button></div><p class="right-help">${dashboard?'Select a view or open a worksheet to refine its marks.':'Drag <b>dimensions</b> and <b>measures</b> to build your view.'}</p></div>
    ${sheet?`<div class="right-section"><h4>${dashboard?'Selected view':'View options'}</h4>${dashboard?`<div class="right-help" style="margin:0 0 12px;color:#8c7da3">${esc(sheet.name)}</div>`:''}<label class="toggle">Show mark labels<input type="checkbox" id="option-labels" ${sheet.showLabels?'checked':''}></label>${sheet.type==='scatter'?`<label class="toggle">Aggregate marks<input type="checkbox" id="option-aggregate" ${sheet.aggregate?'checked':''}></label><label class="right-label">Point size<input type="range" id="option-point-size" min="2" max="16" value="${sheet.pointSize??5}"></label>`:''}<label class="right-label">Opacity<input type="range" id="option-opacity" min="15" max="100" value="${Math.round((sheet.opacity??.9)*100)}"></label><label class="right-label">Sort by<select id="option-sort"><option value="desc" ${sheet.sort==='desc'?'selected':''}>Value ↓</option><option value="asc" ${sheet.sort==='asc'?'selected':''}>Value ↑</option><option value="alpha" ${sheet.sort==='alpha'?'selected':''}>A → Z</option><option value="none" ${sheet.sort==='none'?'selected':''}>Unsorted</option></select></label><label class="right-label">Mark limit<input id="option-limit" type="number" value="${sheet.limit??100000}" min="1" max="2000000" step="1000"></label></div>`:''}
    ${dashboard?`<div class="right-section"><h4>Dashboard</h4><label class="toggle">Use views as filters<input type="checkbox" id="option-linked" ${dashboard.linked?'checked':''}></label><label class="toggle">Edit layout<input type="checkbox" id="option-layout" ${dashboardEditing?'checked':''}></label><label class="right-label">Row height<input id="option-row-height" type="number" min="36" max="120" value="${dashboard.rowHeight}"></label>${dashboardEditing?`<div class="sheet-list">${workbook.sheets.map(s=>`<button data-add-tile="${esc(s.id)}">${icon(s.type)}<span>${esc(s.name)}</span><small>+</small></button>`).join('')}</div>`:''}</div>`:''}
    <div class="right-section" id="right-legend"><h4>${esc(legendField??'Color')}</h4><div class="legend-list" id="legend-list"></div></div><div class="right-section" style="border:0"><div class="insight-note">${icon('sparkle')}<strong>${dashboard?'A connected perspective':'Let the data lead.'}</strong>${dashboard?'Click any mark to filter the other views. Ctrl / ⌘-click to select more.':'Drop a field on Color, Size, or Detail to reveal another dimension.'}</div></div>`;
  const controls={'option-labels':['showLabels',e=>e.target.checked],'option-aggregate':['aggregate',e=>e.target.checked],'option-opacity':['opacity',e=>+e.target.value/100],'option-point-size':['pointSize',e=>+e.target.value],'option-sort':['sort',e=>e.target.value],'option-limit':['limit',e=>Math.max(1,Math.min(2000000,+e.target.value||100000))]};for(const [id,[key,value]]of Object.entries(controls))$(`#${id}`)?.addEventListener('change',e=>mutate(`change ${key}`,()=>{activeSheet()[key]=value(e);}));
  $('#option-linked')?.addEventListener('change',e=>mutate('change linked filters',()=>{activeDashboard().linked=e.target.checked;selection=null;}));$('#option-layout')?.addEventListener('change',()=>toggleDashboardEdit());$('#option-row-height')?.addEventListener('change',e=>mutate('resize dashboard rows',()=>activeDashboard().rowHeight=Math.max(36,Math.min(120,+e.target.value||59))));
}
function pillHTML(pill,slot,index,sheet){const f=fieldInfo(sourceFor(sheet),pill);if(!f)return '';const isMeasure=f.role==='measure'||['count','countd'].includes(pill.agg);const name=isMeasure?`${(pill.agg??'sum').toUpperCase()}(${pill.field})`:pill.field;return `<div class="field-pill ${isMeasure?'measure':''}" draggable="true" data-pill-slot="${slot}" data-pill-index="${index}" data-field="${esc(pill.field)}" data-source="${esc(sheet.source)}" data-sheet="${esc(sheet.id)}"><span>${esc(name)}</span><button title="Field options" class="pill-menu">⌄</button><button title="Remove field" class="pill-remove">×</button></div>`;}
function renderWorksheet(){const sheet=activeSheet();if(!sheet){$('#workspace-content').innerHTML='<div class="empty-workspace">Create a worksheet to begin.</div>';return;}const source=sourceFor(sheet);
  const shelf=(name,label)=>`<div class="shelf"><span class="shelf-label">${icon(name)}${label}</span><div class="shelf-content drop-target" data-drop="${name}">${sheet[name].map((p,i)=>pillHTML(p,name,i,sheet)).join('')||`<span class="shelf-placeholder">Drop ${name==='columns'?'a dimension or measure':'a measure or dimension'} here</span>`}</div></div>`;
  $('#workspace-content').innerHTML=`<div class="worksheet-layout"><div class="shelves">${shelf('columns','Columns')}${shelf('rows','Rows')}</div><div class="worksheet-body"><aside class="cards-pane"><div class="card"><div class="card-title">Filters ${icon('filter')}</div><div class="card-content drop-target" data-drop="filters">${sheet.filters.map((f,i)=>`<button class="field-pill" data-filter-index="${i}"><span>${esc(f.field??'Selection')}</span>⌄</button>`).join('')||'<span class="card-empty">Drop fields here<br>to filter your view</span>'}</div></div><div class="card"><div class="card-title">Marks <span>⌄</span></div><select class="mark-select" id="marks-type">${Object.entries(typeName).map(([t,n])=>`<option value="${t}" ${t===sheet.type?'selected':''}>${n}</option>`).join('')}</select><div class="mark-slots">${['color','size','label','detail'].map(slot=>`<button class="mark-slot drop-target ${sheet.marks[slot]?'active':''}" data-drop="${slot}" data-choose-mark="${slot}">${icon(slot)}<span>${slot[0].toUpperCase()+slot.slice(1)}</span></button>`).join('')}</div><div class="mark-fields">${Object.entries(sheet.marks).filter(([,p])=>p).map(([slot,p])=>`<div class="mark-field-row">${icon(slot)}${pillHTML(p,slot,0,sheet)}</div>`).join('')}</div></div><div class="right-help" style="padding:0 5px;font-size:9px">${icon('info')} Changes to this worksheet update every dashboard that uses it.</div></aside><div class="canvas-region"><div class="worksheet-header"><div><h1 id="worksheet-title" title="Double-click to rename">${esc(sheet.name)}</h1><p>${esc(source.name)} <span style="padding:0 5px;color:#d2d4df">/</span> <span id="worksheet-summary">Computing your view…</span></p></div><button class="tile-menu" data-action="sheet-menu" title="Worksheet options">•••</button></div><div class="selection-strip worksheet-selection" id="selection-strip"></div><div class="worksheet-chart" id="main-chart"></div><div class="worksheet-footer"><span id="worksheet-footer-stats">Live query · All records</span><button data-action="preview-results">View underlying data ${icon('arrow')}</button></div></div></div></div>`;
  addChartView('main',$('#main-chart'),sheet);$('#marks-type').onchange=e=>changeChartType(e.target.value);$('#worksheet-title').ondblclick=()=>renameSheet(sheet.id);renderSelectionStrip();
}
function renderDashboard(){const d=activeDashboard();if(!d)return;const source=workbook.sources.find(s=>s.id===d.source)??activeSource();
  $('#workspace-content').innerHTML=`<div class="dashboard-wrap"><div class="dashboard-eyebrow">${icon('dashboard')} Executive overview <span style="color:#c0b6d6">/</span> Retail intelligence</div><div class="dashboard-title-row"><div><h1 id="dashboard-title" title="Double-click to edit dashboard title">${esc(d.title??d.name)}</h1><p class="dashboard-subtitle">${esc(d.subtitle??'Connected views. Clearer decisions.')}</p></div><div class="dashboard-header-right"><span class="date-badge">${icon('calendar')}<span id="date-range-caption">All dates</span><span>⌄</span></span><button class="dashboard-edit ${dashboardEditing?'active':''}" data-action="edit-dashboard">${icon('edit')}${dashboardEditing?'Done editing':'Edit layout'}</button></div></div><div class="selection-strip" id="selection-strip" style="display:${selection?'flex':'none'}"></div><div class="metrics-row" id="dashboard-metrics">${[1,2,3,4].map(()=>`<div class="metric-card"><div class="metric-label">Calculating… ${icon('info')}</div><div class="metric-value">—</div><div class="metric-bottom">Querying source records</div></div>`).join('')}</div><div class="dashboard-grid" id="dashboard-grid"></div><div class="dashboard-footnote">${icon('link')}${d.linked?'Views are linked. Click a mark to explore across the dashboard.':'Linked filtering is off.'}<span style="margin-left:auto">${source.sample?'Synthetic sample · Computed from transactions':'Local data · Private by default'}</span></div></div>`;
  const grid=$('#dashboard-grid');const gap=14;grid.style.height=`${Math.max(4,...d.tiles.map(t=>t.y+t.h))*d.rowHeight}px`;
  for(const tile of d.tiles){const s=sheetById(tile.sheetId);if(!s)continue;const card=document.createElement('article');card.className=`dashboard-tile ${dashboardEditing?'editing':''}`;card.dataset.tile=tile.id;setTileStyle(card,tile,d.rowHeight,gap);card.innerHTML=`<div class="tile-header"><span class="tile-drag-handle">⠿</span><div class="tile-title">${esc(s.name)}<small>${s.type==='scatter'?'Individual transactions':s.type==='heatmap'?'Segment × region':'Grouped insights'}</small></div><div class="tile-legend" id="legend-${tile.id}"></div><button class="tile-menu" data-tile-menu="${esc(tile.id)}" title="View options">•••</button></div><div class="tile-chart" id="chart-${tile.id}"></div><div class="tile-resize" title="Drag to resize"></div>`;grid.append(card);addChartView(tile.id,card.querySelector('.tile-chart'),s);if(dashboardEditing){card.querySelector('.tile-header').addEventListener('pointerdown',e=>startTileDrag(e,tile,card,false));card.querySelector('.tile-resize').addEventListener('pointerdown',e=>startTileDrag(e,tile,card,true));}card.addEventListener('pointerdown',()=>{if(focusedSheetId!==s.id){focusedSheetId=s.id;renderRightPane();updateLegend(s.id);}});}
  $('#dashboard-title').ondblclick=()=>editDashboardText();renderSelectionStrip();
}
function setTileStyle(card,tile,rowHeight,gap=14){card.style.left=`calc(${tile.x/12*100}% + ${gap/2}px)`;card.style.width=`calc(${tile.w/12*100}% - ${gap}px)`;card.style.top=`${tile.y*rowHeight}px`;card.style.height=`${tile.h*rowHeight-gap}px`;}
function startTileDrag(e,tile,card,resizing){if(e.button!==0||e.target.closest('button'))return;e.preventDefault();const d=activeDashboard(),grid=$('#dashboard-grid'),width=grid.clientWidth,start={x:e.clientX,y:e.clientY,tile:structuredClone(tile)},target=e.currentTarget;target.setPointerCapture(e.pointerId);card.style.zIndex=20;let next={...tile};const move=ev=>{const dx=Math.round((ev.clientX-start.x)/(width/12)),dy=Math.round((ev.clientY-start.y)/d.rowHeight);next=resizing?{...tile,w:Math.max(3,Math.min(12-tile.x,start.tile.w+dx)),h:Math.max(3,start.tile.h+dy)}:{...tile,x:Math.max(0,Math.min(12-tile.w,start.tile.x+dx)),y:Math.max(0,start.tile.y+dy)};setTileStyle(card,next,d.rowHeight);};const end=ev=>{target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',end);target.removeEventListener('pointercancel',end);if(target.hasPointerCapture(ev.pointerId))target.releasePointerCapture(ev.pointerId);card.style.zIndex='';if(JSON.stringify(next)!==JSON.stringify(tile))mutate(resizing?'resize dashboard tile':'move dashboard tile',()=>{Object.assign(tile,next);resolveTileCollisions(d,tile);});};target.addEventListener('pointermove',move);target.addEventListener('pointerup',end);target.addEventListener('pointercancel',end);}
function resolveTileCollisions(d,moved){const overlaps=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;const placed=[moved];for(const t of d.tiles.filter(t=>t.id!==moved.id).sort((a,b)=>a.y-b.y)){let collision;while((collision=placed.find(p=>overlaps(t,p))))t.y=collision.y+collision.h;placed.push(t);}}
function toggleDashboardEdit(){if(!activeDashboard())return;dashboardEditing=!dashboardEditing;renderAll();}
function addChartView(id,host,sheet){const chart=new ChartView(host,{onMode:mode=>{currentMode=mode==='WebGPU'||[...views.values()].some(v=>v.chart.surface.mode==='WebGPU'&&v.chart.surface.gpu&&!v.chart.surface.gpu.lost)?'WebGPU':'Canvas2D';$('#engine-badge').innerHTML=`<i></i>${currentMode==='WebGPU'?'WebGPU accelerated':'Canvas2D fallback'}`;$('#engine-badge').classList.toggle('gpu',currentMode==='WebGPU');},onSelect:event=>handleSelection(sheet.id,event)});views.set(id,{chart,sheetId:sheet.id,host});}
async function refreshQueries(){
  if(!workbook||workbook.active.kind==='data')return;const epoch=++queryEpoch,selectionSnapshot=selection,entries=[...views.values()],unique=[...new Set(entries.map(v=>v.sheetId))];let totalMarks=0,totalTime=0,totalScanned=0;
  for(const id of unique){const s=sheetById(id);if(!s)continue;const source=sourceFor(s),{spec,layout}=chartQuery(s,source,activeDashboard()?.linked===false?null:selectionSnapshot);try{const result=await rpc.call('query',spec);if(epoch!==queryEpoch)return;result._measures=spec.measures;const model=chartModel(s,source,result,layout,selectionSnapshot);results.set(id,{result,spec,layout,model});for(const v of entries.filter(v=>v.sheetId===id))v.chart.set(model);totalMarks+=model.records.length;totalTime+=result.stats.elapsed;totalScanned+=result.stats.scannedRows;updateLegend(id);if(workbook.active.kind==='sheet'){$('#worksheet-summary').textContent=`${count(result.stats.matchedRows)} records · ${count(result.rows.length)} marks`;$('#worksheet-footer-stats').textContent=`${count(result.stats.matchedRows)} of ${count(result.stats.sourceRows)} rows · ${result.stats.mode}${result.stats.truncated?` · Showing ${count(result.rows.length)} of ${count(result.stats.totalMarks)} marks`:''}`;}}catch(error){if(epoch!==queryEpoch)return;for(const v of entries.filter(v=>v.sheetId===id)){v.chart.set({type:s.type,records:[]});v.host.dataset.error=error.message;}toast(`${s.name}: ${error.message}`,'error');}}
  if(epoch!==queryEpoch)return;$('#status-marks').textContent=`${count(totalMarks)} marks`;$('#status-rows').textContent=`${count(activeSource().rows)} source rows`;$('#query-status').textContent=`${totalTime.toFixed(1)} ms · ${count(totalScanned)} rows scanned`;
  if(activeDashboard())await refreshMetrics(epoch);
}
function updateLegend(sheetId){const cached=results.get(sheetId);if(!cached)return;const series=[...new Set(cached.model.records.map(r=>r.series).filter(v=>v!=null))];for(const [id,v]of views)if(v.sheetId===sheetId&&$(`#legend-${id}`))$(`#legend-${id}`).innerHTML=series.length<=3?series.map(s=>`<span><i style="background:${colorFor(s)}"></i>${esc(s)}</span>`).join(''):'';
  if(activeSheet()?.id===sheetId&&$('#legend-list')){if(series.length)$('#legend-list').innerHTML=series.slice(0,18).map(s=>`<div class="legend-row"><i style="background:${colorFor(s)}"></i><span>${esc(s)}</span></div>`).join('')+(series.length>18?`<div class="right-help">+ ${series.length-18} more</div>`:'');else if(cached.model.type==='heatmap')$('#legend-list').innerHTML='<div style="height:7px;background:linear-gradient(90deg,#efebfd,#694fc3);border-radius:3px"></div><div style="display:flex;justify-content:space-between;font-size:9px;color:#a4a0b1"><span>Lower</span><span>Higher</span></div>';else $('#legend-list').innerHTML='<div class="legend-row"><i style="background:#7561d4"></i><span>All records</span></div>';}
}
async function refreshMetrics(epoch){const d=activeDashboard();if(!d)return;const source=workbook.sources.find(s=>s.id===d.source)??activeSource(),numbers=source.schema.filter(f=>f.type==='number');const sales=numbers.find(f=>f.name==='Sales')??numbers[0],profit=numbers.find(f=>f.name==='Profit')??numbers[1];const measures=[{field:'*',op:'count',as:'records'}];if(sales)measures.push({field:sales.name,op:'sum',as:'first'});if(profit)measures.push({field:profit.name,op:'sum',as:'second'});const filters=selection?.tableId===source.id&&d.linked?[selection.filter]:[];const result=await rpc.call('query',{tableId:source.id,dimensions:[],measures,filters});if(epoch!==queryEpoch||!$('#dashboard-metrics'))return;const r=result.rows[0]??{},isMoney=sales?.name==='Sales';const cards=[{label:sales?`Total ${sales.name.toLowerCase()}`:'Records',value:sales?(isMoney?'$':'')+formatNumber(r.first,true):count(r.records??0),note:sales?`SUM(${sales.name})`:'COUNT(Records)',tag:'Aggregate'}, {label:profit?`Total ${profit.name.toLowerCase()}`:'Numeric fields',value:profit?(profit.name==='Profit'?'$':'')+formatNumber(r.second,true):String(numbers.length),note:profit?`SUM(${profit.name})`:'Detected in source',tag:profit?'Aggregate':'Schema'}, {label:sales&&profit?profit.name==='Profit'&&sales.name==='Sales'?'Profit margin':`${profit.name} / ${sales.name}`:'Source completeness',value:sales&&profit?r.first?formatNumber(r.second/r.first*100)+'%':'—':formatNumber((r.records??0)/Math.max(1,source.rows)*100)+'%',note:sales&&profit?'Ratio of sums, not averages':'Selected rows / all rows',tag:'Calculated'}, {label:'Total records',value:count(r.records??0),note:selection?'After linked selection':'Across the current extract',tag:'Live'}];$('#dashboard-metrics').innerHTML=cards.map(c=>`<div class="metric-card"><div class="metric-label">${esc(c.label)} ${icon('info')}</div><div class="metric-value">${esc(c.value)}</div><div class="metric-bottom"><span>${c.tag}</span>${esc(c.note)}</div></div>`).join('');
  const dateField=source.schema.find(f=>f.type==='date');if(dateField&&$('#date-range-caption')){const dateInfo=await rpc.call('distinct',{tableId:source.id,field:dateField.name});if(epoch===queryEpoch&&$('#date-range-caption')&&dateInfo.min!=null){const formatter=new Intl.DateTimeFormat('en-US',{month:'short',year:'numeric',timeZone:'UTC'});$('#date-range-caption').textContent=`${formatter.format(dateInfo.min)} – ${formatter.format(dateInfo.max)}`;}}
}
function handleSelection(sheetId,event){const sheet=sheetById(sheetId);if(!sheet)return;if(activeDashboard()?.linked===false)return;focusedSheetId=sheetId;const cached=results.get(sheetId);if(event.brush){const {xMeasure,yMeasure}=cached.layout;if(!xMeasure||!yMeasure)return;selection={sheetId,tableId:sheet.source,keys:[],label:`${xMeasure.field} & ${yMeasure.field} range`,filter:{op:'and',filters:[{field:xMeasure.field,op:'between',min:event.brush.x[0],max:event.brush.x[1]},{field:yMeasure.field,op:'between',min:event.brush.y[0],max:event.brush.y[1]}]}};}else if(event.record){const r=event.record,previous=event.multi&&selection?.sheetId===sheetId?selection.records??[]:[];let records=previous.some(p=>p.key===r.key)?previous.filter(p=>p.key!==r.key):[...previous,r];if(!event.multi&&selection?.sheetId===sheetId&&selection.keys?.length===1&&selection.keys[0]===r.key)records=[];if(!records.length)selection=null;else{const predicates=records.map(record=>{const filters=Object.entries(record.keys).map(([field,value])=>({field,op:'eq',value}));if(cached.spec.raw&&cached.layout.xMeasure&&cached.layout.yMeasure&&!filters.some(f=>/id$/i.test(f.field))){filters.push({field:cached.layout.xMeasure.field,op:'eq',value:record.x},{field:cached.layout.yMeasure.field,op:'eq',value:record.y});}return {op:'and',filters};});selection={sheetId,tableId:sheet.source,records,keys:records.map(r=>r.key),label:records.length===1?records[0].label:`${records.length} selected marks`,filter:{op:'or',filters:predicates}};}}else selection=null;
  renderSelectionStrip();renderRightPane();updateLegend(sheetId);refreshQueries().catch(fail);
}
function renderSelectionStrip(){const strip=$('#selection-strip');if(!strip)return;strip.style.display=selection?'flex':'none';strip.innerHTML=selection?`${icon('filter')}<span class="selection-chip">${esc(selection.label)}<button data-action="clear-selection" aria-label="Clear selection">×</button></span><span>Filtering linked views</span><button class="clear-selection" data-action="clear-selection">Clear</button>`:'';}

function showMenu(anchor,items){closeMenu();const menu=document.createElement('div');menu.className='context-menu';for(const item of items){if(item==='-'){menu.append(document.createElement('hr'));continue;}if(item.heading){const label=document.createElement('div');label.className='context-label';label.textContent=item.heading;menu.append(label);continue;}if(item.note){const note=document.createElement('p');note.textContent=item.note;menu.append(note);continue;}const button=document.createElement('button');button.type='button';button.className=`${item.active?'active':''} ${item.danger?'danger':''}`;button.innerHTML=`<span>${esc(item.label)}</span>${item.shortcut?`<small>${esc(item.shortcut)}</small>`:''}`;button.disabled=!!item.disabled;button.onclick=()=>{closeMenu();Promise.resolve(item.action?.()).catch(fail);};menu.append(button);}$('#menu-root').append(menu);const rect=anchor instanceof Element?anchor.getBoundingClientRect():{left:anchor.x,bottom:anchor.y};menu.style.left=Math.max(6,Math.min(rect.left,innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.max(6,Math.min(rect.bottom+4,innerHeight-menu.offsetHeight-8))+'px';}
function closeMenu(){$('#menu-root').replaceChildren();}
function showModal(title,html,{wide=false,buttons=[{text:'Done',primary:true,action:closeModal}]}={}){closeMenu();$('#modal').classList.toggle('wide',wide);$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;$('#modal-footer').replaceChildren();for(const item of buttons){const b=document.createElement('button');b.type='button';b.className=`btn ${item.primary?'primary':''} ${item.danger?'danger':''}`;b.textContent=item.text;b.disabled=!!item.disabled;if(item.id)b.id=item.id;b.onclick=async()=>{b.disabled=true;try{await item.action?.();}catch(e){fail(e);}finally{b.disabled=false;}};$('#modal-footer').append(b);}if(!$('#modal').open)$('#modal').showModal();}
function closeModal(){$('#modal').close();}
function inputDialog(title,label,value,onApply,{description='',multiline=false}={}){showModal(title,`<label class="form-field"><span>${esc(label)}</span>${multiline?`<textarea id="dialog-input">${esc(value)}</textarea>`:`<input id="dialog-input" value="${esc(value)}" required maxlength="180">`}</label>${description?`<p class="help-text">${esc(description)}</p>`:''}`,{buttons:[{text:'Cancel',action:closeModal},{text:'Apply',primary:true,action:()=>{const v=$('#dialog-input').value.trim();if(!v)throw new Error('Please enter a value.');onApply(v);closeModal();}}]});setTimeout(()=>{$('#dialog-input').focus();$('#dialog-input').select();},0);}
function confirmDialog(title,description,action){showModal(title,`<p>${esc(description)}</p>`,{buttons:[{text:'Cancel',action:closeModal},{text:'Continue',primary:true,action:async()=>{await action();closeModal();}}]});}
function download(name,content,mime){const blob=content instanceof Blob?content:new Blob([content],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
const safeFilename=s=>s.replace(/[^\p{L}\p{N}_. -]/gu,'_').slice(0,120);
function fileMenu(anchor){showMenu(anchor,[{label:'New sample workbook',action:newSampleWorkbook},{label:'Open workbook…',shortcut:'Ctrl/⌘ O',action:()=>$('#workbook-file-input').click()},'-',{label:'Save locally',shortcut:'Ctrl/⌘ S',action:()=>saveLocal()},{label:'Download workbook…',action:exportWorkbook},'-',{label:'Import CSV / JSON…',action:()=>$('#data-file-input').click()},{label:'Export data & visualizations…',action:exportDialog},'-',{label:'Workbook settings…',action:()=>inputDialog('Workbook settings','Workbook name',workbook.name,name=>mutate('rename workbook',()=>workbook.name=name))}]);}
function dataMenu(anchor){showMenu(anchor,[{label:'Connect data…',action:()=>$('#data-file-input').click()},{label:'Preview active data source',action:()=>previewData()},'-',{label:'Create calculated field…',action:()=>calculationDialog()},{label:'Create group…',action:()=>groupDialog()},{label:'Join data sources…',action:joinDialog},'-',{label:'Append CSV / JSON…',action:()=>$('#append-file-input').click()},{label:'Append 1,000 sample transactions',action:()=>appendSample(),disabled:!activeSource()?.sample||!activeSource()?.schema.some(f=>f.name==='Sales')},{label:'Generate 100,000-row sample',action:()=>generateLargeSample(100000)},'-',{label:'Data source information',action:sourceInfo}]);}
function worksheetMenu(anchor,sheet=activeSheet()){showMenu(anchor,[{label:'New worksheet',action:createWorksheet},{label:'Duplicate worksheet',action:()=>duplicateWorksheet(sheet?.id),disabled:!sheet},{label:'Rename worksheet…',action:()=>renameSheet(sheet.id),disabled:!sheet},'-',{label:'Swap rows and columns',action:()=>swapShelves(),disabled:!sheet},{label:'Clear worksheet',action:()=>clearWorksheet(),disabled:!sheet},{label:'View result data',action:()=>previewResults(sheet?.id),disabled:!sheet},{label:'Inspect query plan',action:()=>analysisDialog(sheet?.id),disabled:!sheet},'-',{label:'Delete worksheet',danger:true,action:()=>deleteWorksheet(sheet.id),disabled:!sheet||workbook.sheets.length<=1}]);}
function dashboardMenu(anchor){const d=activeDashboard();showMenu(anchor,[{label:'New dashboard',action:createDashboard},{label:'Edit dashboard layout',action:toggleDashboardEdit,disabled:!d},{label:'Edit title & description…',action:editDashboardText,disabled:!d},{label:'Rename dashboard tab…',action:()=>inputDialog('Rename dashboard','Tab name',d.name,v=>mutate('rename dashboard',()=>d.name=v)),disabled:!d},'-',{label:'Clear linked selection',action:clearSelection,disabled:!selection},{label:'Delete dashboard',danger:true,disabled:!d,action:()=>confirmDialog('Delete dashboard?',`The worksheets in ${d.name} will be kept.`,()=>mutate('delete dashboard',()=>{workbook.dashboards=workbook.dashboards.filter(x=>x.id!==d.id);workbook.active={kind:'sheet',id:workbook.sheets[0].id};}))}]);}
function fieldMenu(anchor,field){const source=activeSource(),f=fieldInfo(source,{field}),def=source.definitions.find(d=>d.name===field);showMenu(anchor,[{heading:`${f.type} · ${f.role}`},{label:'Add to Columns',action:()=>addField(field,'columns',source.id)},{label:'Add to Rows',action:()=>addField(field,'rows',source.id)},{label:'Add to Color',action:()=>addField(field,'color',source.id)},{label:'Filter…',action:()=>filterDialog(field)},'-',{label:`Convert to ${f.role==='measure'?'dimension':'measure'}`,disabled:f.type!=='number'&&f.role==='dimension',action:()=>mutate('change field role',()=>source.roles[field]=f.role==='measure'?'dimension':'measure')},{label:'Create group…',action:()=>groupDialog(field)},{label:'Create calculated field…',action:()=>calculationDialog(null,`[${field.replaceAll(']',']]')}]`)},...(def?.kind==='calculation'?[{label:'Edit calculated field…',action:()=>calculationDialog(def)}]:[]),...(def?['-',{label:'Delete derived field',danger:true,action:()=>deleteDerivedField(source,field)}]:[])]);}
function pillMenu(anchor,slot,index){const sheet=activeSheet(),pill=['columns','rows'].includes(slot)?sheet[slot][index]:sheet.marks[slot],source=sourceFor(sheet),f=fieldInfo(source,pill);if(!pill)return;const aggregations=f.type==='number'?['sum','avg','min','max','count','countd','stdev']:['count','countd'];showMenu(anchor,[{heading:pill.field},...aggregations.map(agg=>({label:({sum:'Sum',avg:'Average',min:'Minimum',max:'Maximum',count:'Count (non-null)',countd:'Count distinct',stdev:'Sample standard deviation'})[agg],active:(pill.agg??(f.role==='measure'?'sum':''))===agg,action:()=>mutate('change aggregation',()=>{pill.agg=agg;pill.role='measure';})})),{label:'Use as discrete dimension',active:f.role==='dimension'&&!pill.agg,action:()=>mutate('make field discrete',()=>{delete pill.agg;pill.role='dimension';})},'-',{label:'Filter this field…',action:()=>filterDialog(pill.field)},{label:'Remove from view',danger:true,action:()=>removePill(slot,index)}]);}
function removePill(slot,index){mutate('remove field',()=>{const s=activeSheet();if(['columns','rows'].includes(slot))s[slot].splice(index,1);else s.marks[slot]=null;});}
function ensureAuthoringSheet(sourceId){let s=activeSheet();if(!s){s=newSheet(workbook.sources.find(x=>x.id===sourceId));workbook.sheets.push(s);workbook.active={kind:'sheet',id:s.id};}return s;}
function addField(field,slot,sourceId=activeSource().id,from){
  const source=workbook.sources.find(s=>s.id===sourceId);if(!source)throw new Error('The field source is missing.');
  if(slot==='filters'){const s=activeSheet();if(s&&s.source!==sourceId){toast('Select a worksheet using this data source before adding its filters.');return;}filterDialog(field);return;}
  mutate(`add ${field} to ${slot}`,()=>{const s=ensureAuthoringSheet(sourceId);if(s.source!==sourceId){s.source=sourceId;s.columns=[];s.rows=[];s.filters=[];s.marks={color:null,size:null,label:null,detail:null};selection=null;}
    const info=fieldInfo(source,{field}),pill={field,...(info.role==='measure'?{agg:'sum'}:{})};
    if(from&&from.sheet===s.id){const current=['columns','rows'].includes(from.slot)?s[from.slot][from.index]:s.marks[from.slot];if(current)Object.assign(pill,current);if(['columns','rows'].includes(from.slot))s[from.slot].splice(from.index,1);else s.marks[from.slot]=null;}
    if(['columns','rows'].includes(slot)){if(s[slot].length>=8)throw new Error('A shelf supports up to eight fields.');if(!s[slot].some(p=>p.field===field&&p.agg===pill.agg))s[slot].push(pill);}else s.marks[slot]=pill;
    workbook.activeSource=sourceId;focusedSheetId=s.id;
    if(workbook.active.kind!=='sheet'){workbook.active={kind:'sheet',id:s.id};dashboardEditing=false;}
  });
}
function chooseMarkField(anchor,slot){const source=sourceFor(activeSheet());showMenu(anchor,[{heading:`Assign ${slot}`},...source.schema.filter(f=>slot==='size'?f.type==='number':true).map(f=>({label:f.name,action:()=>addField(f.name,slot,source.id)}))]);}
function autoAddField(field,sourceId){const source=workbook.sources.find(s=>s.id===sourceId),f=fieldInfo(source,{field});addField(field,f.role==='measure'?'columns':'rows',sourceId);}
function changeChartType(type){let sheet=activeSheet();if(!sheet){createWorksheet();sheet=activeSheet();}mutate(`change chart to ${type}`,()=>{const source=sourceFor(sheet),dims=source.schema.filter(f=>fieldInfo(source,f.name).role==='dimension'),nums=source.schema.filter(f=>fieldInfo(source,f.name).role==='measure');const existing=[...sheet.columns,...sheet.rows],dimension=existing.find(p=>fieldInfo(source,p)?.role==='dimension')??(dims[0]?{field:dims[0].name}:null),metric=existing.find(p=>fieldInfo(source,p)?.role==='measure')??(nums[0]?measurePill(nums[0].name):null);sheet.type=type;
    if(type==='scatter'){sheet.columns=metric?[{...metric,agg:metric.agg??'avg'}]:[];const y=nums.find(f=>f.name!==metric?.field)??nums[0];sheet.rows=y?[measurePill(y.name,'avg')]:[];sheet.aggregate=false;sheet.showLabels=false;sheet.opacity=.58;sheet.marks.color=sheet.marks.color??(dims.find(f=>/category|region|segment/i.test(f.name))?{field:dims.find(f=>/category|region|segment/i.test(f.name)).name}:null);}
    else if(type==='heatmap'){const x=dims.find(f=>f.name==='Region')??dims[0],y=dims.find(f=>f.name==='Segment'&&f.name!==x?.name)??dims.find(f=>f.name!==x?.name);sheet.columns=x?[{field:x.name}]:[];sheet.rows=y?[{field:y.name}]:[];sheet.marks.color=metric;sheet.showLabels=true;}
    else if(type==='line'){const time=dims.find(f=>f.name==='Month')??dims.find(f=>f.type==='date')??dimension;sheet.columns=time?[{field:time.name??time.field}]:[];sheet.rows=metric?[metric]:[];sheet.aggregate=true;sheet.showLabels=false;sheet.sort='alpha';if(sheet.marks.color?.field===sheet.columns[0]?.field)sheet.marks.color=null;}
    else {sheet.rows=dimension?[dimension]:[];sheet.columns=metric?[metric]:[];sheet.aggregate=true;sheet.showLabels=true;if(sheet.marks.color&&fieldInfo(source,sheet.marks.color)?.role==='measure'&&type==='bar')sheet.marks.color=null;}
    selection=null;
  });}
function createWorksheet(){mutate('create worksheet',()=>{const s=newSheet(activeSource(),`Sheet ${workbook.sheets.length+1}`);workbook.sheets.push(s);workbook.active={kind:'sheet',id:s.id};focusedSheetId=s.id;selection=null;});}
function duplicateWorksheet(id=activeSheet()?.id){if(!id)return;mutate('duplicate worksheet',()=>{const s=structuredClone(sheetById(id));s.id=uid('sheet');s.name+=' (copy)';workbook.sheets.push(s);workbook.active={kind:'sheet',id:s.id};focusedSheetId=s.id;});}
function renameSheet(id){const s=sheetById(id);inputDialog('Rename worksheet','Worksheet name',s.name,name=>mutate('rename worksheet',()=>s.name=name));}
function deleteWorksheet(id){const s=sheetById(id);confirmDialog('Delete worksheet?',`“${s.name}” and its dashboard tiles will be removed.`,()=>mutate('delete worksheet',()=>{workbook.sheets=workbook.sheets.filter(s=>s.id!==id);for(const d of workbook.dashboards)d.tiles=d.tiles.filter(t=>t.sheetId!==id);if(workbook.active.id===id)workbook.active={kind:'sheet',id:workbook.sheets[0].id};focusedSheetId=workbook.sheets[0].id;}));}
function clearWorksheet(){const s=activeSheet();if(!s)return;mutate('clear worksheet',()=>{s.columns=[];s.rows=[];s.marks={color:null,size:null,label:null,detail:null};s.filters=[];selection=null;});}
function swapShelves(){const s=activeSheet();if(s)mutate('swap shelves',()=>[s.columns,s.rows]=[s.rows,s.columns]);}
function createDashboard(){mutate('create dashboard',()=>{const d={id:uid('dashboard'),name:`Dashboard ${workbook.dashboards.length+1}`,title:'A new perspective.',subtitle:'Bring your worksheets together. Make the connections.',source:activeSource().id,linked:true,rowHeight:59,tiles:workbook.sheets.slice(0,4).map((s,i)=>({id:uid('tile'),sheetId:s.id,x:i%2*6,y:Math.floor(i/2)*4,w:6,h:4}))};workbook.dashboards.push(d);workbook.active={kind:'dashboard',id:d.id};selection=null;dashboardEditing=true;});}
function editDashboardText(){const d=activeDashboard();if(!d)return;showModal('Dashboard details',`<label class="form-field"><span>Title</span><input id="dash-title-input" value="${esc(d.title??d.name)}" maxlength="150"></label><label class="form-field"><span>Description</span><textarea id="dash-subtitle-input">${esc(d.subtitle??'')}</textarea></label>`,{buttons:[{text:'Cancel',action:closeModal},{text:'Save',primary:true,action:()=>{const title=$('#dash-title-input').value.trim(),subtitle=$('#dash-subtitle-input').value.trim();if(!title)throw new Error('A title is required.');mutate('edit dashboard title',()=>{d.title=title;d.subtitle=subtitle;});closeModal();}}]});}
function addDashboardTile(sheetId){const d=activeDashboard();if(!d)return;mutate('add dashboard tile',()=>{d.tiles.push({id:uid('tile'),sheetId,x:0,y:Math.max(0,...d.tiles.map(t=>t.y+t.h)),w:6,h:4});});}
function tileMenu(anchor,tileId){const d=activeDashboard(),tile=d.tiles.find(t=>t.id===tileId),s=sheetById(tile.sheetId);focusedSheetId=s.id;showMenu(anchor,[{heading:s.name},{label:'Open worksheet',action:()=>setActive('sheet',s.id)},{label:'View result data',action:()=>previewResults(s.id)},{label:'Inspect query plan',action:()=>analysisDialog(s.id)},{label:'Export SVG',action:()=>exportSVG(tileId)},'-',{label:'Edit dashboard layout',action:toggleDashboardEdit},{label:'Remove from dashboard',danger:true,action:()=>mutate('remove dashboard tile',()=>d.tiles=d.tiles.filter(t=>t.id!==tileId))}]);}
function clearSelection(){selection=null;renderSelectionStrip();refreshQueries().catch(fail);}

async function filterDialog(field,index=null){
  const sheet=activeSheet();if(!sheet)throw new Error('Create a worksheet before adding a filter.');const source=sourceFor(sheet);if(!source.schema.some(f=>f.name===field))throw new Error('This field is not in the selected worksheet’s data source.');
  const existing=index!=null?sheet.filters[index]:sheet.filters.find(f=>f.field===field),at=index??sheet.filters.findIndex(f=>f.field===field),info=await rpc.call('distinct',{tableId:source.id,field});
  const apply=filter=>{mutate(`filter ${field}`,()=>{if(at>=0)sheet.filters.splice(at,1);if(filter)sheet.filters.push(filter);selection=null;});closeModal();};
  if(info.type==='number'||info.type==='date'){
    const isDate=info.type==='date',fmt=v=>v==null?'':isDate?new Date(v).toISOString().slice(0,10):String(v),inputType=isDate?'date':'number';
    showModal(`Filter: ${field}`,`<p>Keep source rows in this inclusive range. The filter runs <strong>before aggregation</strong>.</p><div class="form-row"><label><span>Minimum</span><input type="${inputType}" id="filter-min" value="${fmt(existing?.min)}" placeholder="${fmt(info.min)}" ${isDate?'':'step="any"'}></label><label><span>Maximum</span><input type="${inputType}" id="filter-max" value="${fmt(existing?.max)}" placeholder="${fmt(info.max)}" ${isDate?'':'step="any"'}></label></div><div class="help-text">Source range: ${esc(fmt(info.min))} to ${esc(fmt(info.max))} · ${count(info.nulls)} null values.<br>Empty bounds are unbounded. A range filter excludes nulls.</div>`,{buttons:[{text:'Remove filter',action:()=>apply(null)},{text:'Cancel',action:closeModal},{text:'Apply filter',primary:true,action:()=>{const a=$('#filter-min').value,b=$('#filter-max').value,min=a===''?null:isDate?Date.parse(a):Number(a),max=b===''?null:isDate?Date.parse(b)+86399999:Number(b);if(min!=null&&max!=null&&min>max)throw new Error('The minimum cannot exceed the maximum.');apply({field,op:'between',min,max});}}]});return;
  }
  const entries=info.values,selected=new Set((existing?.op==='in'?existing.values:entries.map(e=>e.value)).map(v=>JSON.stringify(v)));let search='';
  showModal(`Filter: ${field}`,`<p>Select the values to include in this worksheet.</p><label class="form-field"><input id="filter-search" placeholder="Search values"></label><div class="filter-tools"><button type="button" id="filter-select-all">Select visible</button><span>·</span><button type="button" id="filter-select-none">Clear visible</button><span id="filter-selected-count" style="margin-left:auto"></span></div><div class="checklist" id="filter-checklist"></div><div class="help-text" id="filter-list-note"></div>`,{buttons:[{text:'Remove filter',action:()=>apply(null)},{text:'Cancel',action:closeModal},{text:'Apply filter',primary:true,action:()=>{const values=entries.filter(v=>selected.has(JSON.stringify(v.value))).map(v=>v.value);apply(values.length===entries.length?null:{field,op:'in',values});}}]});
  const visible=()=>entries.filter(e=>String(e.value??'(Null)').toLowerCase().includes(search));
  const redraw=()=>{const list=visible();$('#filter-checklist').innerHTML=list.slice(0,2000).map(e=>`<label class="check-row"><input type="checkbox" data-key="${esc(JSON.stringify(e.value))}" ${selected.has(JSON.stringify(e.value))?'checked':''}><span>${esc(e.value??'(Null)')}</span><small>${count(e.count)}</small></label>`).join('');$('#filter-selected-count').textContent=`${count(selected.size)} of ${count(entries.length)} selected`;$('#filter-list-note').textContent=list.length>2000?`Showing the first 2,000 matching values. Search to narrow the list; bulk selection affects all ${count(list.length)} matching values.`:'';};
  $('#filter-search').oninput=e=>{search=e.target.value.toLowerCase();redraw();};$('#filter-select-all').onclick=()=>{visible().forEach(e=>selected.add(JSON.stringify(e.value)));redraw();};$('#filter-select-none').onclick=()=>{visible().forEach(e=>selected.delete(JSON.stringify(e.value)));redraw();};$('#filter-checklist').onchange=e=>{const key=e.target.dataset.key;if(e.target.checked)selected.add(key);else selected.delete(key);$('#filter-selected-count').textContent=`${count(selected.size)} of ${count(entries.length)} selected`;};redraw();
}
async function calculationDialog(def=null,initialExpression=''){
  const source=activeSource(),numeric=source.schema.filter(f=>f.type==='number');const formula=(def?.expression??initialExpression)||(source.schema.some(f=>f.name==='Profit')&&source.schema.some(f=>f.name==='Sales')?'IF [Sales] > 0 THEN [Profit] / [Sales] ELSE NULL END':numeric.length?`[${numeric[0].name}] * 1.1`:'1');let valid=false,validationId=0,debounce;
  showModal(def?'Edit calculated field':'Create calculated field',`<label class="form-field"><span>Field name</span><input id="calc-name" maxlength="150" value="${esc(def?.name??'New calculation')}" ${def?'readonly':''}></label><label class="form-field"><span>Row-level expression</span><textarea id="calc-expression" spellcheck="false">${esc(formula)}</textarea></label><div class="expression-functions">${['IF','ROUND','ABS','COALESCE','YEAR','DATETRUNC','CONCAT'].map(f=>`<button type="button" class="function-chip" data-function="${f}">${f}</button>`).join('')}</div><div id="calc-validation" class="expression-status">Checking the expression…</div><div id="calc-preview" class="expression-preview"></div><p class="help-text">Use <code>[Field name]</code> references. Calculations are type-checked and run in the data worker without <code>eval</code>. Nulls propagate; division by zero produces null. Add the resulting field to a shelf to aggregate it.</p><details><summary>Supported functions</summary><p class="help-text">${expressionFunctions.join(', ')}</p><p class="help-text">Conditional syntax: IF condition THEN result ELSE alternative END. Aggregations belong on shelves, not inside row calculations.</p></details>`,{buttons:[{text:'Cancel',action:closeModal},{text:'Create field',primary:true,id:'calc-apply',action:async()=>{const name=$('#calc-name').value.trim(),expression=$('#calc-expression').value.trim();if(!name)throw new Error('Enter a calculated field name.');if(!def&&source.schema.some(f=>f.name===name))throw new Error('That field name already exists.');await rpc.call('validateExpression',{tableId:source.id,expression});const definitions=structuredClone(source.definitions),newDef={kind:'calculation',name,expression};if(def)definitions[definitions.findIndex(d=>d.name===def.name)]=newDef;else definitions.push(newDef);const desc=await rpc.call('definitions',{tableId:source.id,definitions});history.push(workbook,def?'edit calculation':'create calculation');updateDescription(desc);markChanged(true);renderAll();closeModal();toast(`Calculated field “${name}” is ready to use.`,'success');}}]});
  if(def)$('#calc-apply').textContent='Save calculation';
  const validate=async()=>{const id=++validationId;try{const result=await rpc.call('validateExpression',{tableId:source.id,expression:$('#calc-expression').value});if(id!==validationId||!$('#calc-validation'))return;valid=true;$('#calc-validation').className='expression-status valid';$('#calc-validation').textContent=`✓ Valid expression · Returns ${result.type} · ${result.dependencies.length} field dependencies · ${result.bytecode.length} VM instructions`;$('#calc-preview').textContent=`First five rows: ${result.preview.map(v=>v==null?'NULL':result.type==='date'?new Date(v).toISOString().slice(0,10):displayValue(v)).join('  ·  ')}`;$('#calc-apply').disabled=false;}catch(error){if(id!==validationId||!$('#calc-validation'))return;valid=false;$('#calc-validation').className='expression-status invalid';$('#calc-validation').textContent=error.message;$('#calc-preview').textContent='';$('#calc-apply').disabled=true;}};
  $('#calc-expression').oninput=()=>{clearTimeout(debounce);$('#calc-apply').disabled=true;debounce=setTimeout(validate,180);};$$('[data-function]').forEach(button=>button.onclick=()=>{const input=$('#calc-expression'),f=button.dataset.function,text=f==='IF'?'IF condition THEN value ELSE value END':f+'()';input.setRangeText(text,input.selectionStart,input.selectionEnd,'end');input.focus();validate();});await validate();
}
async function groupDialog(initialField){
  const source=activeSource(),dims=source.schema.filter(f=>fieldInfo(source,f.name).role==='dimension');if(!dims.length)throw new Error('The data source has no dimension fields to group.');let selected=new Set(),values=[],current=initialField??dims[0].name;
  showModal('Create a group',`<div class="form-row"><label><span>Dimension</span><select id="group-field">${source.schema.map(f=>`<option value="${esc(f.name)}" ${f.name===current?'selected':''}>${esc(f.name)}</option>`).join('')}</select></label><label><span>New field name</span><input id="group-name" value="${esc(current)} (group)" maxlength="150"></label></div><label class="form-field"><span>Group label for selected members</span><input id="group-label" value="My group"></label><label class="form-field"><input id="group-search" placeholder="Search members"></label><div class="checklist" id="group-members"></div><p class="help-text">Selected members receive the group label. All other values keep their original labels. Groups are materialized as a reusable dimension and also apply to appended rows.</p>`,{buttons:[{text:'Cancel',action:closeModal},{text:'Create group',primary:true,action:async()=>{const name=$('#group-name').value.trim(),label=$('#group-label').value.trim();if(!name||!label||!selected.size)throw new Error('Enter a field name, a group label, and select at least one member.');if(source.schema.some(f=>f.name===name))throw new Error('That field name already exists.');const definitions=[...source.definitions,{kind:'group',name,field:current,label,members:values.filter(v=>selected.has(JSON.stringify(v.value))).map(v=>v.value)}];const desc=await rpc.call('definitions',{tableId:source.id,definitions});history.push(workbook,'create group');updateDescription(desc);markChanged(true);renderAll();closeModal();toast(`Group “${name}” created.`,'success');}}]});
  const redraw=()=>{const search=$('#group-search').value.toLowerCase();$('#group-members').innerHTML=values.filter(v=>String(v.value??'(Null)').toLowerCase().includes(search)).slice(0,2000).map(v=>`<label class="check-row"><input type="checkbox" data-key="${esc(JSON.stringify(v.value))}" ${selected.has(JSON.stringify(v.value))?'checked':''}><span>${esc(v.value??'(Null)')}</span><small>${count(v.count)}</small></label>`).join('');};
  const load=async()=>{current=$('#group-field').value;selected=new Set();$('#group-name').value=`${current} (group)`;values=(await rpc.call('distinct',{tableId:source.id,field:current})).values;if(!$('#group-members'))return;if(selection?.records)for(const r of selection.records)if(Object.hasOwn(r.keys,current))selected.add(JSON.stringify(r.keys[current]));redraw();};
  $('#group-field').onchange=()=>load().catch(fail);$('#group-search').oninput=redraw;$('#group-members').onchange=e=>{e.target.checked?selected.add(e.target.dataset.key):selected.delete(e.target.dataset.key);};await load();
}
async function deleteDerivedField(source,field){const used=workbook.sheets.some(s=>s.source===source.id&&[...s.columns,...s.rows,...Object.values(s.marks).filter(Boolean)].some(p=>p.field===field));confirmDialog('Delete derived field?',used?'This field will also be removed from worksheet shelves and filters. Other calculated fields that depend on it must be removed first.':`Delete “${field}” from this source?`,async()=>{const definitions=source.definitions.filter(d=>d.name!==field),desc=await rpc.call('definitions',{tableId:source.id,definitions});history.push(workbook,'delete derived field');updateDescription(desc);for(const s of workbook.sheets.filter(s=>s.source===source.id)){s.rows=s.rows.filter(p=>p.field!==field);s.columns=s.columns.filter(p=>p.field!==field);s.filters=s.filters.filter(p=>p.field!==field);for(const k of Object.keys(s.marks))if(s.marks[k]?.field===field)s.marks[k]=null;}markChanged(true);renderAll();});}
async function joinDialog(){
  if(workbook.sources.length<2){showModal('Connect another data source',`<p>Import a second CSV or JSON source, then use the join editor to combine them by one or more typed keys.</p>`,{buttons:[{text:'Cancel',action:closeModal},{text:'Import data',primary:true,action:()=>{closeModal();$('#data-file-input').click();}}]});return;}
  let left=activeSource().id,right=workbook.sources.find(s=>s.id!==left).id;
  const sourceOptions=id=>workbook.sources.map(s=>`<option value="${esc(s.id)}" ${s.id===id?'selected':''}>${esc(s.name)} (${count(s.rows)} rows)</option>`).join('');
  showModal('Join data sources',`<div class="form-row"><label><span>Left source</span><select id="join-left">${sourceOptions(left)}</select></label><label><span>Right source</span><select id="join-right">${sourceOptions(right)}</select></label></div><div class="form-row"><label><span>Join type</span><select id="join-kind"><option value="left">Left outer · keep all left rows</option><option value="inner">Inner · matching rows only</option><option value="full">Full outer · keep both sides</option></select></label><label><span>Output source name</span><input id="join-name" value="Joined data"></label></div><div id="join-pairs"></div><button type="button" class="btn" id="join-add-key">+ Add key pair</button><div class="inline-alert">Joins use exact, type-matched keys. Null keys do not match each other. Duplicate keys produce all matching row pairs; many-to-many joins can increase the row count.</div><p class="help-text">This creates a materialized source. The original sources remain unchanged. Re-run the join after appending to an input. Output is limited to 2,000,000 rows.</p>`,{buttons:[{text:'Cancel',action:closeModal},{text:'Run join',primary:true,action:async()=>{const name=$('#join-name').value.trim();if(!name)throw new Error('Enter an output name.');const leftKeys=$$('.join-left-key').map(e=>e.value),rightKeys=$$('.join-right-key').map(e=>e.value),kind=$('#join-kind').value;$('#modal-footer .primary').textContent='Joining…';const desc=await rpc.call('join',{id:uid('source'),name,leftId:left,rightId:right,leftKeys,rightKeys,kind});history.push(workbook,'join sources');workbook.sources.push(sourceFromDescription(desc));workbook.activeSource=desc.id;const sheet=newSheet(desc,`${name} analysis`),dim=desc.schema.find(f=>f.role==='dimension'),metric=desc.schema.find(f=>f.role==='measure');if(dim)sheet.rows=[{field:dim.name}];if(metric)sheet.columns=[measurePill(metric.name)];workbook.sheets.push(sheet);workbook.active={kind:'data',id:desc.id};selection=null;markChanged(true);renderAll();closeModal();toast(`Join produced ${count(desc.rows)} rows. ${count(desc.joinStats.unmatchedLeft)} left rows had no match.`,'success');}}]});
  const pair=()=>{const ls=workbook.sources.find(s=>s.id===left),rs=workbook.sources.find(s=>s.id===right),common=ls.schema.find(l=>rs.schema.some(r=>r.name===l.name&&r.type===l.type));const row=document.createElement('div');row.className='form-row join-pair';row.innerHTML=`<label><span>Left key</span><select class="join-left-key">${ls.schema.map(f=>`<option value="${esc(f.name)}" ${f.name===common?.name?'selected':''}>${esc(f.name)} · ${f.type}</option>`).join('')}</select></label><span style="align-self:center;padding-top:14px;color:#baabcb">=</span><label><span>Right key</span><select class="join-right-key">${rs.schema.map(f=>`<option value="${esc(f.name)}" ${f.name===common?.name?'selected':''}>${esc(f.name)} · ${f.type}</option>`).join('')}</select></label><button type="button" title="Remove key pair" style="padding-bottom:9px">×</button>`;row.querySelector('button').onclick=()=>{if($$('.join-pair').length>1)row.remove();};$('#join-pairs').append(row);};
  $('#join-left').onchange=e=>{left=e.target.value;$('#join-pairs').replaceChildren();pair();};$('#join-right').onchange=e=>{right=e.target.value;$('#join-pairs').replaceChildren();pair();};$('#join-add-key').onclick=pair;pair();
}
async function importFiles(files){for(const file of files){if(file.size>256*1024*1024)throw new Error('Import files must be smaller than 256 MB.');toast(`Importing ${file.name}…`);const id=uid('source'),name=file.name.replace(/\.(csv|tsv|json)$/i,''),text=await file.text(),format=/\.json$/i.test(file.name)?'json':'csv';const desc=await rpc.call('import',{id,name,text,format});history.push(workbook,'import data');workbook.sources.push(sourceFromDescription(desc));workbook.activeSource=id;const created=genericWorkbook(desc).sheets[0];workbook.sheets.push(created);workbook.active={kind:'sheet',id:created.id};focusedSheetId=created.id;selection=null;markChanged(true);renderAll();toast(`Imported ${count(desc.rows)} rows and ${desc.schema.length} fields from ${file.name}.`,'success');}$('#data-file-input').value='';}
async function appendFile(file){if(!file)return;const source=activeSource(),text=await file.text(),before=await rpc.call('snapshot'),desc=await rpc.call('append',{tableId:source.id,text,format:/\.json$/i.test(file.name)?'json':'csv'});history.push(workbook,'append rows');history.undoStack.at(-1).data=before;updateDescription(desc);markChanged(true);renderAll();toast(`Appended ${count(desc.rows-source.rows)} rows. Cached aggregates will scan only the new rows.`,'success');$('#append-file-input').value='';}
async function appendSample(){const source=activeSource();if(!source.sample||!source.schema.some(f=>f.name==='Sales'))throw new Error('Sample appends are available only for the generated retail source.');const before=await rpc.call('snapshot'),desc=await rpc.call('append',{tableId:source.id,sample:true,count:1000});history.push(workbook,'append sample rows');history.undoStack.at(-1).data=before;updateDescription(desc);markChanged(true);renderAll();toast('Appended 1,000 transactions. Open Query plan to inspect incremental scans.','success');}
async function generateLargeSample(rows){toast(`Generating ${count(rows)} synthetic transactions in the worker…`);const id=uid('source'),desc=await rpc.call('sample',{id,name:`Retail benchmark · ${count(rows)} rows`,count:rows});history.push(workbook,'generate benchmark source');desc.sample=true;workbook.sources.push(sourceFromDescription(desc));workbook.activeSource=id;const s=defaultWorkbook(desc).sheets[2];s.name=`${count(rows)} transaction scatter`;workbook.sheets.push(s);workbook.active={kind:'sheet',id:s.id};focusedSheetId=s.id;selection=null;markChanged(true);renderAll();toast(`${count(rows)} source rows ready. Rendering individual transactions.`,'success');}
async function newSampleWorkbook(){confirmDialog('Start a fresh workbook?','The current workbook will be replaced. Download it first to keep a portable copy.',async()=>{await initializeSample();history.clear();selection=null;markChanged(true);renderAll();});}
async function initializeSample(){await rpc.call('reset');const id=uid('source'),desc=await rpc.call('sample',{id,name:'Retail transactions',count:7200});desc.sample=true;workbook=defaultWorkbook(desc);const regions=await rpc.call('add',{id:uid('source'),name:'Regional targets',rows:[{Region:'West','Account lead':'Alex Morgan','Annual target':1250000},{Region:'East','Account lead':'Sam Chen','Annual target':1150000},{Region:'Central','Account lead':'Jordan Ellis','Annual target':1000000},{Region:'South','Account lead':'Casey Reid','Annual target':950000}]});regions.sample=true;workbook.sources.push(sourceFromDescription(regions));dataDirty=true;}
async function exportWorkbook(){const snapshots=await rpc.call('snapshot'),ids=new Set(workbook.sources.map(s=>s.id));const file={...structuredClone(workbook),exportedAt:new Date().toISOString(),datasets:snapshots.filter(s=>ids.has(s.id))};download(`${safeFilename(workbook.name)}.lattice`,JSON.stringify(file),'application/json');toast('Portable workbook exported with data, calculations, sheets, and layouts.','success');}
async function openWorkbook(file){if(!file)return;const json=JSON.parse(await file.text());validateWorkbook(json);if(!Array.isArray(json.datasets)||json.sources.some(s=>!json.datasets.some(d=>d.id===s.id)))throw new Error('This workbook is missing its source datasets.');const {datasets,...metadata}=json;for(const source of metadata.sources){const data=datasets.find(d=>d.id===source.id);data.definitions=source.definitions??[];}await rpc.call('restore',{sources:datasets});workbook=metadata;history.clear();selection=null;focusedSheetId=null;await syncDefinitions();markChanged(true);renderAll();$('#workbook-file-input').value='';toast(`Opened “${workbook.name}”.`,'success');}
function exportSVG(viewId){const view=viewId?views.get(viewId):[...views.values()].find(v=>v.sheetId===activeSheet()?.id)??views.values().next().value;if(!view)throw new Error('Open a worksheet or dashboard before exporting a chart.');const name=sheetById(view.sheetId)?.name??'Chart';download(`${safeFilename(name)}.svg`,view.chart.toSVG(name),'image/svg+xml');toast('Exported the visualization as editable SVG.','success');}
function exportDialog(){const s=activeSheet();showModal('Export your work',`<p>Your data stays in this browser until you choose to export it.</p><label class="form-field"><span>Format</span><select id="export-format"><option value="workbook">Lattice workbook · all data and editable views</option><option value="csv-results">CSV · active worksheet query results</option><option value="json-results">JSON · active worksheet query results</option><option value="csv-source">CSV · full active data source</option><option value="json-source">JSON · full active data source</option><option value="svg">SVG · active visualization</option></select></label><div class="help-text">Worksheet exports contain the grouped or raw marks currently queried, including filters and the mark limit. Source exports contain all source records, including materialized calculations.<br><br>CSV exports preserve values exactly. Treat untrusted text beginning with spreadsheet formula characters as text when opening it in spreadsheet software.</div>`,{buttons:[{text:'Cancel',action:closeModal},{text:'Export',primary:true,action:async()=>{const format=$('#export-format').value;if(format==='workbook')await exportWorkbook();else if(format==='svg')exportSVG();else{let rows,name;if(format.endsWith('results')){if(!s||!results.has(s.id))throw new Error('Open a worksheet first.');const cached=results.get(s.id);rows=humanizeResults(cached);name=s.name;}else{rows=await rpc.call('export',{tableId:activeSource().id});name=activeSource().name;}const json=format.startsWith('json');download(`${safeFilename(name)}.${json?'json':'csv'}`,json?JSON.stringify(rows,null,2):toCSV(rows),json?'application/json':'text/csv;charset=utf-8');toast(`Exported ${count(rows.length)} records.`,'success');}closeModal();}}]});}
function humanizeResults(cached){return cached.result.rows.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>{const m=cached.spec.measures.find(m=>m.as===k);return [m?`${cached.spec.raw?'':m.op.toUpperCase()+'('}${m.field==='*'?'Records':m.field}${cached.spec.raw?'':')'}`:k==='__rowId'?'Source row index':k,v];})));}
function dataTableHTML(rows,schema){const columns=schema?.map(f=>f.name)??Object.keys(rows[0]??{});if(!columns.length)return '<div class="help-text" style="padding:20px">No records matched the current query.</div>';return `<table class="data-table"><thead><tr><th>#</th>${columns.map(name=>`<th>${esc(name)}</th>`).join('')}</tr></thead><tbody>${rows.map((row,i)=>`<tr><td style="color:#b8afc2">${i+1}</td>${columns.map(name=>`<td class="${typeof row[name]==='number'?'numeric ':''}${row[name]==null?'null':''}" title="${esc(row[name]??'NULL')}">${esc(row[name]??'NULL')}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
async function previewData(offset=0){const source=activeSource(),result=await rpc.call('preview',{tableId:source.id,offset,limit:100});showModal(`Data preview · ${source.name}`,`<div class="table-meta"><span>Rows ${result.rows.length?offset+1:0}–${Math.min(offset+100,result.total)} of ${count(result.total)}</span><span>${result.schema.length} fields · Worker-backed columnar data</span></div><div class="data-table-container">${dataTableHTML(result.rows,result.schema)}</div><p class="help-text">Dates use ISO 8601; nulls are shown explicitly. Calculated and grouped fields appear alongside imported columns.</p>`,{wide:true,buttons:[{text:'Previous 100',disabled:offset===0,action:()=>previewData(Math.max(0,offset-100))},{text:'Next 100',disabled:offset+100>=result.total,action:()=>previewData(offset+100)},{text:'Close',primary:true,action:closeModal}]});}
function previewResults(id=activeSheet()?.id){const cached=results.get(id);if(!cached)throw new Error('No query results yet. Open a worksheet first.');const rows=humanizeResults(cached);showModal(`Query results · ${sheetById(id).name}`,`<div class="table-meta"><span>${count(rows.length)} result records · ${count(cached.result.stats.matchedRows)} matched source rows</span><span>Showing first ${Math.min(500,rows.length)} records</span></div><div class="data-table-container">${dataTableHTML(rows.slice(0,500))}</div>`,{wide:true,buttons:[{text:'Export CSV',action:()=>download(`${safeFilename(sheetById(id).name)}.csv`,toCSV(rows),'text/csv;charset=utf-8')},{text:'Close',primary:true,action:closeModal}]});}
async function renderDataSource(){const epoch=renderEpoch,source=activeSource();$('#workspace-content').innerHTML=`<div class="data-source-view"><div class="dashboard-eyebrow">${icon('database')} Data workspace</div><h1>Your data, connected.</h1><p>Inspect local extracts, combine sources, and build reusable calculations.</p><div class="source-actions"><button class="btn" data-action="import">${icon('database')}Connect data</button><button class="btn" data-action="join">${icon('join')}Join sources</button><button class="btn" data-action="append">${icon('refresh')}Append records</button><button class="btn" data-action="calculation">ƒx Calculated field</button></div><div class="source-nodes">${workbook.sources.map(s=>`<button class="source-node ${source.id===s.id?'active':''}" data-select-source="${esc(s.id)}"><strong>${icon('database')} ${esc(s.name)}</strong><span>${count(s.rows)} rows · ${s.schema.length} columns · ${formatNumber(s.bytes/1048576)} MB</span></button>`).join('')}</div><div class="table-meta"><span>${esc(source.name)} · First 100 records</span><button data-action="preview" style="font-size:10px;color:#a58ab8">Open paginated preview ↗</button></div><div class="data-table-container" id="source-table"><div style="padding:20px" class="help-text">Reading typed columns…</div></div><div class="table-meta"><span>${source.sample?'Synthetic demonstration data. Every chart is computed from the source rows.':'Imported data stays local. No network requests are made by the analytics engine.'}</span></div>${source.joinStats?`<div class="inline-alert">Join: ${count(source.joinStats.leftRows)} left × ${count(source.joinStats.rightRows)} right → ${count(source.joinStats.outputRows)} output rows. ${count(source.joinStats.unmatchedLeft)} unmatched left keys, ${count(source.joinStats.unmatchedRight)} unmatched right rows.</div>`:''}</div>`;try{const data=await rpc.call('preview',{tableId:source.id,limit:100});if(epoch===renderEpoch&&$('#source-table'))$('#source-table').innerHTML=dataTableHTML(data.rows,data.schema);}catch(e){fail(e);}$('#status-marks').textContent=`${source.schema.length} fields`;$('#status-rows').textContent=`${count(source.rows)} source rows`;$('#query-status').textContent=`${formatNumber(source.bytes/1048576)} MB columnar storage`;}
function sourceInfo(){const source=activeSource();showModal(`Source information · ${source.name}`,`<div class="plan-stats"><div><b>${count(source.rows)}</b>rows</div><div><b>${source.schema.length}</b>typed columns</div><div><b>${formatNumber(source.bytes/1048576)} MB</b>column buffers + dictionaries</div><div><b>${source.definitions.length}</b>derived fields</div></div><div class="data-table-container"><table class="data-table"><thead><tr><th>Field</th><th>Type</th><th>Role</th><th>Nulls</th><th>Storage</th></tr></thead><tbody>${source.schema.map(f=>`<tr><td>${esc(f.name)}</td><td>${f.type}</td><td>${fieldInfo(source,f.name).role}</td><td>${count(f.nulls??0)}</td><td>${f.type==='string'?'Uint32 dictionary codes':f.type==='boolean'?'Uint8':'Float64'} + validity</td></tr>`).join('')}</tbody></table></div><p class="help-text">Memory shown excludes query caches, worker message copies, and JavaScript object overhead. Numeric precision is IEEE 754 double precision; this is not a fixed-decimal accounting engine.</p>`,{wide:true});}
function analysisDialog(id=activeSheet()?.id){const c=results.get(id);if(!c)throw new Error('Open a worksheet to inspect its executed plan.');const {stats}=c.result;showModal(`Query plan · ${sheetById(id).name}`,`<div class="plan-stats"><div><b>${stats.elapsed.toFixed(2)} ms</b>worker query time</div><div><b>${count(stats.scannedRows)}</b>rows scanned this run</div><div><b>${count(stats.matchedRows)}</b>rows matched in total</div><div><b>${esc(stats.mode)}</b>aggregation state</div></div>${c.result.plan.map((p,i)=>{const {operator,...detail}=p;return `<div class="plan-operator"><header><span>${i+1}</span>${operator}</header><pre>${esc(JSON.stringify(detail,null,2))}</pre></div>`;}).join('')}<p class="help-text">Row filters run before aggregation. Sort and limit run after aggregation. A cache hit scans zero rows; an append-only update scans the new suffix. Derived-field changes invalidate affected source caches. Query time excludes worker messaging, chart layout, and GPU submission.</p>`,{wide:true,buttons:[{text:'Export plan JSON',action:()=>download('query-plan.json',JSON.stringify({spec:c.spec,plan:c.result.plan,stats},null,2),'application/json')},{text:'Close',primary:true,action:closeModal}]});}
function helpDialog(){showModal('A little guidance. A lot of possibility.',`<div class="shortcut-grid"><span>Save workbook locally</span><span><kbd>Ctrl / ⌘</kbd> <kbd>S</kbd></span><span>Open a portable workbook</span><span><kbd>Ctrl / ⌘</kbd> <kbd>O</kbd></span><span>Undo / Redo</span><span><kbd>Ctrl / ⌘ Z</kbd> / <kbd>Shift Z</kbd></span><span>Clear linked selection</span><span><kbd>Esc</kbd></span><span>Multi-select chart marks</span><span><kbd>Ctrl / ⌘</kbd> + click</span><span>Brush a scatter plot</span><span><kbd>Shift</kbd> + drag</span><span>Add a field automatically</span><span>Double-click a field</span></div><div class="workbook-info"><strong>Build a worksheet</strong><br>Drag a dimension to Rows and a measure to Columns. Use the pill menu to change aggregation. Add Color, Size, Label, or Detail. Drop any field on Filters.<br><br><strong>Connect your views</strong><br>Open a dashboard and click a mark to filter other worksheets using the same source. “Edit layout” enables tile moving and resizing on a 12-column grid. Add worksheets from the right pane while editing.<br><br><strong>Make it yours</strong><br>Import CSV/JSON, create typed calculated fields, group members, or materialize inner/left/full joins. Changes are undoable. Data and workbook metadata are saved to IndexedDB; export a .lattice file for a portable copy.</div><p class="help-text">Lattice is an original, independent implementation inspired by desktop visual analytics workflows. It does not read Tableau .twb/.twbx files or connect to Tableau Server. The included retail data is synthetic.</p><p class="help-text">WebGPU is used when available. Canvas2D is an explicitly identified fallback. Desktop keyboard and mouse are recommended for authoring; dashboard views can also be inspected with touch.</p>`,{wide:false});}

const actions={
  undo:()=>historyStep('undo'),redo:()=>historyStep('redo'),save:()=>saveLocal(),import:()=>$('#data-file-input').click(),append:()=>$('#append-file-input').click(),
  'new-sheet':createWorksheet,'duplicate-sheet':()=>duplicateWorksheet(),'clear-sheet':clearWorksheet,swap:swapShelves,
  'sort-asc':()=>activeSheet()&&mutate('sort ascending',()=>activeSheet().sort='asc'),'sort-desc':()=>activeSheet()&&mutate('sort descending',()=>activeSheet().sort='desc'),
  calculation:()=>calculationDialog(),group:()=>groupDialog(),join:joinDialog,export:exportDialog,
  'new-dashboard':createDashboard,'edit-dashboard':toggleDashboardEdit,'clear-selection':clearSelection,
  'toggle-show-me':()=>{$('#right-pane').classList.toggle('hidden');$('#show-me-toggle').classList.toggle('active');},
  'data-tab':()=>{analyticsTab=false;renderFields();},'analytics-tab':()=>{analyticsTab=true;renderFields();},
  preview:()=>previewData(),'preview-results':()=>previewResults(),'source-info':sourceInfo,
  'data-source':()=>setActive('data',activeSource().id),analysis:()=>analysisDialog(),format:()=>{$('#right-pane').classList.remove('hidden');renderRightPane();},
  help:helpDialog,'sheet-menu':e=>worksheetMenu(e.target.closest('button'))
};
document.addEventListener('click',e=>{
  const action=e.target.closest('[data-action]');if(action){e.preventDefault();Promise.resolve().then(()=>actions[action.dataset.action]?.(e)).catch(fail);return;}
  const menu=e.target.closest('[data-menu]');if(menu){({file:fileMenu,data:dataMenu,worksheet:worksheetMenu,dashboard:dashboardMenu})[menu.dataset.menu]?.(menu);return;}
  const fieldOption=e.target.closest('.field-options');if(fieldOption){fieldMenu(fieldOption,fieldOption.closest('[data-field]').dataset.field);return;}
  const pill=e.target.closest('.field-pill');if(pill){if(e.target.closest('.pill-remove'))removePill(pill.dataset.pillSlot,+pill.dataset.pillIndex);else if(e.target.closest('.pill-menu'))pillMenu(pill,pill.dataset.pillSlot,+pill.dataset.pillIndex);else if(pill.dataset.filterIndex!=null){const i=+pill.dataset.filterIndex;filterDialog(activeSheet().filters[i].field,i).catch(fail);}return;}
  const open=e.target.closest('[data-open-sheet]');if(open){setActive('sheet',open.dataset.openSheet);return;}
  const dash=e.target.closest('[data-open-dashboard]');if(dash){setActive('dashboard',dash.dataset.openDashboard);return;}
  const chartType=e.target.closest('[data-chart-type]');if(chartType){changeChartType(chartType.dataset.chartType);return;}
  const markSlot=e.target.closest('[data-choose-mark]');if(markSlot){chooseMarkField(markSlot,markSlot.dataset.chooseMark);return;}
  const tile=e.target.closest('[data-tile-menu]');if(tile){tileMenu(tile,tile.dataset.tileMenu);return;}
  const addTile=e.target.closest('[data-add-tile]');if(addTile){addDashboardTile(addTile.dataset.addTile);return;}
  const selectSource=e.target.closest('[data-select-source]');if(selectSource){mutate('select data source',()=>{workbook.activeSource=selectSource.dataset.selectSource;workbook.active={kind:'data',id:workbook.activeSource};});return;}
  if(!e.target.closest('.context-menu'))closeMenu();
});
document.addEventListener('dblclick',e=>{const field=e.target.closest('.field-item');if(field)try{autoAddField(field.dataset.field,field.dataset.source);}catch(err){fail(err);}});
document.addEventListener('contextmenu',e=>{const field=e.target.closest('.field-item'),tab=e.target.closest('[data-open-sheet]');if(field){e.preventDefault();fieldMenu({x:e.clientX,y:e.clientY},field.dataset.field);}else if(tab){e.preventDefault();worksheetMenu({x:e.clientX,y:e.clientY},sheetById(tab.dataset.openSheet));}});
document.addEventListener('dragstart',e=>{const field=e.target.closest('[draggable=true][data-field]');if(!field)return;const data={field:field.dataset.field,source:field.dataset.source,from:field.dataset.pillSlot?{slot:field.dataset.pillSlot,index:+field.dataset.pillIndex,sheet:field.dataset.sheet}:null};e.dataTransfer.setData('application/x-lattice-field',JSON.stringify(data));e.dataTransfer.setData('text/plain',field.dataset.field);e.dataTransfer.effectAllowed=field.dataset.pillSlot?'move':'copy';});
document.addEventListener('dragover',e=>{const target=e.target.closest('.drop-target');if(target){e.preventDefault();e.dataTransfer.dropEffect='copy';target.classList.add('drag-over');}});
document.addEventListener('dragleave',e=>{const target=e.target.closest('.drop-target');if(target&&!target.contains(e.relatedTarget))target.classList.remove('drag-over');});
document.addEventListener('dragend',()=>$$('.drag-over').forEach(e=>e.classList.remove('drag-over')));
document.addEventListener('drop',e=>{const target=e.target.closest('.drop-target');$$('.drag-over').forEach(e=>e.classList.remove('drag-over'));if(!target)return;e.preventDefault();try{const text=e.dataTransfer.getData('application/x-lattice-field');if(!text)return;const data=JSON.parse(text);addField(data.field,target.dataset.drop,data.source,data.from);}catch(error){fail(error);}});
document.addEventListener('keydown',e=>{
  if(e.key==='Escape'){closeMenu();if(!$('#modal').open&&selection)clearSelection();return;}
  const typing=e.target instanceof HTMLElement&&e.target.matches('input,textarea,select,[contenteditable=true]');
  if((e.ctrlKey||e.metaKey)&&['s','o','z','y'].includes(e.key.toLowerCase())){const key=e.key.toLowerCase();if((key==='z'||key==='y')&&(typing||$('#modal').open))return;e.preventDefault();if(key==='s')saveLocal().catch(fail);else if(key==='o')$('#workbook-file-input').click();else historyStep(key==='y'||e.shiftKey?'redo':'undo').catch(fail);}
  if(e.key==='Enter'&&e.target.closest('.field-item')){const el=e.target.closest('.field-item');autoAddField(el.dataset.field,el.dataset.source);}
});
$('#field-search').addEventListener('input',e=>{fieldSearch=e.target.value;renderFields();});
$('#source-select').addEventListener('change',e=>mutate('select data source',()=>{workbook.activeSource=e.target.value;if(workbook.active.kind==='data')workbook.active.id=e.target.value;}));
$('#fit-mode').addEventListener('change',e=>{const content=$('#workspace-content');content.style.zoom=e.target.value==='compact'?'.86':'1';$('#right-pane').classList.toggle('hidden',e.target.value==='wide');});
$('#data-file-input').addEventListener('change',e=>importFiles([...e.target.files]).catch(fail));
$('#append-file-input').addEventListener('change',e=>appendFile(e.target.files[0]).catch(fail));
$('#workbook-file-input').addEventListener('change',e=>openWorkbook(e.target.files[0]).catch(fail));
$('#modal-close').onclick=closeModal;$('#modal-form').addEventListener('submit',e=>e.preventDefault());
$('#help-button').onclick=helpDialog;$('.brand').onclick=e=>{e.preventDefault();const d=workbook?.dashboards[0];if(d)setActive('dashboard',d.id);};
$('#workbook-name').ondblclick=()=>inputDialog('Rename workbook','Workbook name',workbook.name,name=>mutate('rename workbook',()=>workbook.name=name));
window.addEventListener('beforeunload',()=>rpc.dispose());
window.addEventListener('error',e=>{if(workbook&&e.message)toast(`Application error: ${e.message}`,'error');});
async function boot(){
  $$('[data-icon]').forEach(el=>el.outerHTML=icon(el.dataset.icon));
  for(const [action,name]of Object.entries({undo:'undo',redo:'redo',save:'save','new-sheet':'sheet','duplicate-sheet':'duplicate','clear-sheet':'clear',swap:'swap','sort-asc':'sort-asc','sort-desc':'sort-desc',group:'group',join:'join'})){const button=$(`.toolbar [data-action="${action}"]`);if(button)button.innerHTML=icon(name);}
  const available=await store.open();let restored=false;
  if(available){try{const metadata=await store.read('metadata','current');if(metadata){validateWorkbook(metadata);const sources=await Promise.all(metadata.sources.map(s=>store.read('sources',s.id)));if(sources.some(s=>!s))throw new Error('Saved source data is missing.');for(const s of sources)s.definitions=metadata.sources.find(x=>x.id===s.id).definitions??[];await rpc.call('restore',{sources});workbook=metadata;restored=true;await syncDefinitions();}}catch(error){toast(`Saved workbook could not be restored: ${error.message}. Opening a fresh sample.`,'error');}}
  if(!restored)await initializeSample();focusedSheetId=workbook.active.kind==='sheet'?workbook.active.id:activeDashboard()?.tiles[0]?.sheetId??workbook.sheets[0]?.id;
  renderAll();$('#boot-screen').classList.add('dismiss');setTimeout(()=>$('#boot-screen').remove(),350);
  if(available){await saveLocal(false);}else{$('#saved-indicator').textContent='File export available';toast('Browser storage is blocked. Use File → Download workbook to keep your changes.');}
  // Diagnostics for reproducible browser tests and performance inspection.
  Object.defineProperty(globalThis,'latticeDebug',{value:Object.freeze({get workbook(){return structuredClone(workbook);},get selection(){return selection?structuredClone(selection):null;},get results(){return new Map(results);},get renderer(){return currentMode;},get viewCount(){return views.size;}})});
}
boot().catch(error=>{fail(error);$('#boot-screen').innerHTML=`<div class="boot-mark">!</div><h1>The workspace could not start.</h1><p style="max-width:560px;text-align:center;line-height:1.7">${esc(error.message)}</p><p>Serve the project over localhost, or open the bundled lattice.html file.</p><button class="btn primary" onclick="location.reload()">Try again</button>`;});
